spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/j
    username: postgres
    password: 123456
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
jwt:
  header: Authorization
  secret: 123
  expiration: 604880